skip-check:
  # "Image Pull Policy should be Always"
  - CKV_K8S_15
  # "The default namespace should not be used"
  - CKV_K8S_21
  # "Image should use digest"
  - CKV_K8S_43
  # "Ensure that HEALTHCHECK instructions have been added to container images"
  - CKV_DOCKER_2
