services:
  health-discovery-hd:
    image: registry.averbis.com/health-discovery/health-discovery:7.0.0-beta-4@sha256:221fd45d6a0daefede6af7853fb831c0636c8edac069fac9bd3c78f3fcc1ba1b
    ports:
      - "${PRODUCT_BIND_ADDR:-0.0.0.0}:${PRODUCT_HTTP_PORT:-9999}:8080"
    environment:
      - PLATFORM_PORT=8080
      - PLATFORM_MAX_MEM=${PRODUCT_MAX_MEM:-24g}
      - DATABASE_DRIVER_CLASS=org.mariadb.jdbc.Driver
      - DATABASE_URL=jdbc:mariadb://database:3306/aif?useMysqlMetadata=true
      - DATABASE_USERNAME=aif
      # kics-scan ignore-line
      - DATABASE_PASSWORD=getaccess
      - SOLR_HOSTNAME=solr
      - SOLR_PORT=8983
    depends_on:
      - database
      - solr
    volumes:
      - resourceVolPlatform-hd:/opt/resources/platform
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health-discovery"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 1m

  database:
    image: docker.io/library/mariadb:11.2.3@sha256:55d9608d84658cbc691f52cd6389386a15e6c671cb5708b9f3af5782af3b4dbb
    command: --max_allowed_packet=1g --innodb_buffer_pool_size=512m --innodb_log_buffer_size=256m --innodb_log_file_size=256m
    environment:
      # kics-scan ignore-line
      - MYSQL_ROOT_PASSWORD=getaccess
      - MYSQL_DATABASE=aif
      - MYSQL_USER=aif
      # kics-scan ignore-line
      - MYSQL_PASSWORD=getaccess

  solr:
    image: registry.averbis.com/solr/solr:9.2.0@sha256:8e0853306e72697252c6ee7190e04629b52860da5ea257314036f0197cce1277
    environment:
      - SOLR_MAX_MEM=512m
      - TEXTANALYSIS_URL=http://${PLATFORM_HOSTNAME:-health-discovery-hd}:${PLATFORM_PORT:-8080}/health-discovery/rest
    volumes:
      - solrDataVol-hd:/opt/solr/server/solr/solrCores
      - solrTermsVol-hd:/opt/solr/server/solr/terms
      - solrLogVol-hd:/opt/solr/server/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/terms/admin/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  kafka:
    image: docker.io/bitnami/kafka:3.6.1@sha256:86b67e37b3d2acf2b2b7fe6e0e73cc5ac560f20627d7e2e6b3ab5eb79c7f5c0b
    profiles:
      - kafka
    restart: unless-stopped
    cap_drop:
      - ALL
    privileged: false
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    environment:
      KAFKA_CFG_NODE_ID: "0"
      KAFKA_RAFT_CLUSTER_ID: "diz-in-a-box"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_MESSAGE_MAX_BYTES: "31457280"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    ports:
      - 9094:9094

  akhq:
    image: tchiotludo/akhq:0.24.0@sha256:6ccf8323ae6e93a893107f857cd9f7210add3569743b2c8528c6567967cc636f
    profiles:
      - kafka
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-compose:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - 8090:8080
    depends_on:
      - kafka

  kafka-data-loader:
    image: confluentinc/cp-kafkacat:7.1.11@sha256:b32a0fc2e8dd0ab25201cc62f856d41a7133e3def9e622471d15383af30b5111
    profiles:
      - kafka
    entrypoint: ["/bin/bash", "-c"]
    command:
      [
        "while true; do kafkacat -b kafka:9092 -t fhir.documents -P -p 0 /data/documentreference.json; sleep 10; done",
      ]
    volumes:
      - ./tests/resources/fhir:/data:ro
    depends_on:
      - kafka

volumes:
  resourceVolPlatform-hd:
    driver: "local"
  dbVol-hd:
    driver: "local"
  solrDataVol-hd:
    driver: "local"
  solrLogVol-hd:
    driver: "local"
  solrTermsVol-hd:
    driver: "local"
