services:
  kafka:
    image: docker.io/bitnami/kafka:3.4.1@sha256:a918700168e7953d70d231466099a859b66c9b09bc9bbbc7b2e445edb004fa14
    restart: unless-stopped
    cap_drop:
      - ALL
    privileged: false
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_MESSAGE_MAX_BYTES: "31457280"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
    ports:
      - 9094:9094

  akhq:
    image: tchiotludo/akhq:0.24.0@sha256:6ccf8323ae6e93a893107f857cd9f7210add3569743b2c8528c6567967cc636f
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - 8090:8080
    depends_on:
      - kafka

  kafka-data-loader:
    image: confluentinc/cp-kafkacat:7.1.7@sha256:e500d5fcad83bfe689941cd676a8191773f17d49267f8de207d8fbc617f6bd24
    entrypoint: ["/bin/bash", "-c"]
    command:
      [
        "while true; do kafkacat -b kafka:9092 -t fhir.documents -P -l /data/documentreference.json; sleep 5; done",
      ]
    volumes:
      - ./tests/resources/fhir:/data:ro
    depends_on:
      - kafka
