services:
  ahd2fhir:
    image: ghcr.io/miracum/ahd2fhir:${IMAGE_TAG:?}
    ports:
      - ${PORT:-8080}:8080
    environment:
      AHD_URL: ${AHD_URL:?}
      AHD_API_TOKEN: ${AHD_API_TOKEN:?}
      AHD_PROJECT: ${AHD_PROJECT:?}
      AHD_PIPELINE: ${AHD_PIPELINE:?}
