version: "3.7"

services:
  zoo1:
    image: zookeeper:3.8.1@sha256:1bcf8e8fdbac2065131b0da25c5a4a1dd7c4961c4031fb3bd1414ebf0a9ef322
    restart: unless-stopped
    hostname: zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181

  kafka1:
    image: confluentinc/cp-kafka:7.4.0@sha256:9080235b1e58a57ca16d480cba6c9cbde72619f2bd43b77d70bada5aecf7811a
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zoo1
  akhq:
    image: tchiotludo/akhq:0.24.0@sha256:6ccf8323ae6e93a893107f857cd9f7210add3569743b2c8528c6567967cc636f
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka1:19092"
    ports:
      - 8090:8080
    depends_on:
      - kafka1

  kafka-data-loader:
    image: confluentinc/cp-kafkacat:7.1.7@sha256:e500d5fcad83bfe689941cd676a8191773f17d49267f8de207d8fbc617f6bd24
    entrypoint: ["/bin/bash", "-c"]
    command:
      [
        "while true; do kafkacat -b kafka1:19092 -t fhir.documents -P -l /data/documentreference.json; sleep 5; done",
      ]
    volumes:
      - ./tests/resources/fhir:/data:ro
    depends_on:
      - kafka1
