version: "3.7"

services:
  mysql-hd:
    image: registry.averbis.com/mysql/mysql:1.17.0
    environment:
      MYSQL_ROOT_PASSWORD: getaccess
      MYSQL_DATABASE: aif
      MYSQL_USER: aif
      MYSQL_PASSWORD: getaccess
      innodb_buffer_pool_size: 512m
      innodb_log_file_size: 256m
      innodb_log_buffer_size: 256m
    volumes:
      - dbVol-hd:/var/lib/mysql

  gcm-hd:
    image: registry.averbis.com/health-discovery/gcm-hd:${PRODUCT_VERSION:-5.35.1}
    environment:
      TOMCAT_XMS: 1g
      TOMCAT_XMX: 2g
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8080/connector-manager/testConnectivity",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  solr-hd:
    image: registry.averbis.com/health-discovery/solr-hd:${PRODUCT_VERSION:-5.35.1}
    environment:
      SOLR_HEAP_SIZE: 512m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/terms/admin/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  health-discovery:
    image: registry.averbis.com/health-discovery/health-discovery:${PRODUCT_VERSION:-5.35.1}
    ports:
      - 127.0.0.1:9999:8080
    environment:
      TOMCAT_XMS: 7g
      TOMCAT_XMX: 8g
    volumes:
      - sharedDirectoryDataVolume-hd:/usr/local/tomcat/shared/pipelines
      - sharedDirectoryDownloads-hd:/usr/local/tomcat/shared/downloads
    depends_on:
      - mysql-hd
      - solr-hd
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health-discovery"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 1m

volumes:
  dbVol-hd:
    driver: "local"
  sharedDirectoryDataVolume-hd:
    driver: "local"
  sharedDirectoryDownloads-hd:
    driver: "local"
