services:
  database:
    image: mariadb:10.5
    command: --max_allowed_packet=1g --innodb_buffer_pool_size=512m
      --innodb_log_buffer_size=256m --innodb_log_file_size=256m
    environment:
      - MYSQL_ROOT_PASSWORD=getaccess
      - MYSQL_DATABASE=aif
      - MYSQL_USER=aif
      - MYSQL_PASSWORD=getaccess
    volumes:
      - dbVol-hd:/var/lib/mysql

  gcm:
    image:  registry.averbis.com/gcm/gcm:7.2.0@sha256:9364cc06cd5b226ac573e3d492c01830e5342c9dfd9caa0cec9b1eb46785e90d
    environment:
      - JAVA_MAX_MEM=2g
      - PLATFORM_HOSTNAME=${PLATFORM_HOSTNAME:-health-discovery-hd}
      - PLATFORM_PORT=${PLATFORM_PORT:-9999}
      - PLATFORM_URL_NAME=health-discovery
      - GCM_HOSTNAME=gcm
      - GCM_PORT=8181
    volumes:
      - gcmVol-hd:/opt/resources/connector-manager/home
      - gcmvoljdbchd:/opt/apache-karaf/lib/ext
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/connector-manager/testConnectivity"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  solr:
    image: registry.averbis.com/solr/solr:7.2.0@sha256:fb70c6ae154fefe7ca32ba96ee15d4fec20daec880dfe8c3e1ca3eefeae1aeaa
    environment:
      - SOLR_MAX_MEM=512m
      - TEXTANALYSIS_URL=http://${PLATFORM_HOSTNAME:-health-discovery-hd}:${PLATFORM_PORT:-9999}/health-discovery/rest
    volumes:
      - solrDataVol-hd:/opt/solr/server/solr/solrCores
      - solrTermsVol-hd:/opt/solr/server/solr/terms
      - solrLogVol-hd:/opt/solr/server/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/terms/admin/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  health-discovery-hd:
    image: registry.averbis.com/health-discovery/health-discovery:6.14.0@sha256:a0335e64890e6858727f25fd3230a5ae05bf3d3fc142d1377ec3e5449df29d47
    ports:
      - "${PRODUCT_BIND_ADDR:-127.0.0.1}:${PRODUCT_HTTP_PORT:-9999}:8080"
    environment:
      - JAVA_OPTS=${HD_JAVA_OPTS}
      - PLATFORM_PORT=8080
      - PLATFORM_MAX_MEM=${PRODUCT_MAX_MEM:-24g}
      - DATABASE_DRIVER_CLASS=org.mariadb.jdbc.Driver
      - DATABASE_URL=jdbc:mariadb://database:3306/aif?useMysqlMetadata=true
      - DATABASE_USERNAME=aif
      - DATABASE_PASSWORD=getaccess
    volumes:
      - resourceVolPlatform-hd:/opt/resources/platform
    depends_on:
      - database
      - solr
      - gcm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/health-discovery"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 1m

volumes:
  resourceVolPlatform-hd:
    driver: "local"
  dbVol-hd:
    driver: "local"
  solrDataVol-hd:
    driver: "local"
  solrLogVol-hd:
    driver: "local"
  solrTermsVol-hd:
    driver: "local"
  gcmVol-hd:
    driver: "local"
  gcmvoljdbchd:
    driver: "local"
