version: "3.7"

services:
  zoo1:
    image: zookeeper:3.7.0
    restart: unless-stopped
    hostname: zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181

  kafka1:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zoo1
  akhq:
    image: tchiotludo/akhq:0.23.0
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka1:19092"
    ports:
      - 8090:8080
    depends_on:
      - kafka1

  kafka-data-loader:
    image: confluentinc/cp-kafkacat:6.2.0
    entrypoint: ["/bin/bash", "-c"]
    command:
      [
        "while true; do kafkacat -b kafka1:19092 -t fhir.documents -P -l /data/documentreference.json; sleep 5; done",
      ]
    volumes:
      - ./tests/resources/fhir:/data:ro
    depends_on:
      - kafka1
