services:
  health-discovery-hd:
    image: registry.averbis.com/health-discovery/health-discovery:6.14.0@sha256:a0335e64890e6858727f25fd3230a5ae05bf3d3fc142d1377ec3e5449df29d47
    ports:
      - "9999:8080"
    environment:
      - PLATFORM_PORT=8080
      - PLATFORM_MAX_MEM=${PRODUCT_MAX_MEM:-24g}
      - DATABASE_DRIVER_CLASS=org.mariadb.jdbc.Driver
      - DATABASE_URL=jdbc:mariadb://database:3306/aif?useMysqlMetadata=true
      - DATABASE_USERNAME=aif
      - DATABASE_PASSWORD=getaccess
    depends_on:
      - database
      - solr
      - gcm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health-discovery"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 1m

  database:
    image: docker.io/library/mariadb:10.11.2@sha256:9ff479f244cc596aed9794d035a9f352662f2caed933238c533024df64569853
    command: --max_allowed_packet=1g --innodb_buffer_pool_size=512m --innodb_log_buffer_size=256m --innodb_log_file_size=256m
    environment:
      - MYSQL_ROOT_PASSWORD=getaccess
      - MYSQL_DATABASE=aif
      - MYSQL_USER=aif
      - MYSQL_PASSWORD=getaccess

  solr:
    image: registry.averbis.com/solr/solr:7.2.0@sha256:fb70c6ae154fefe7ca32ba96ee15d4fec20daec880dfe8c3e1ca3eefeae1aeaa
    environment:
      - SOLR_MAX_MEM=512m
      - TEXTANALYSIS_URL=http://${PLATFORM_HOSTNAME:-health-discovery-hd}:${PLATFORM_PORT:-8080}/health-discovery/rest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/terms/admin/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  gcm:
    image: registry.averbis.com/gcm/gcm:7.2.0@sha256:9364cc06cd5b226ac573e3d492c01830e5342c9dfd9caa0cec9b1eb46785e90d
    environment:
      - JAVA_MAX_MEM=2g
      - PLATFORM_HOSTNAME=${PLATFORM_HOSTNAME:-health-discovery-hd}
      - PLATFORM_PORT=${PLATFORM_PORT:-8080}
      - PLATFORM_URL_NAME=health-discovery
      - GCM_HOSTNAME=gcm
      - GCM_PORT=8181
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8181/connector-manager/testConnectivity",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
