name: check links

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions: read-all

jobs:
  check-links:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: run lychee link checker
        id: lychee
        uses: lycheeverse/lychee-action@97189f2c0a3c8b0cb0e704fd4e878af6e5e2b2c5 # v1.7.0
        with:
          fail: true
          args: "--config=.lychee.toml ."
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
