name: check links

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions: read-all

jobs:
  check-links:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: run lychee link checker
        id: lychee
        uses: lycheeverse/lychee-action@9ace499fe66cee282a29eaa628fdac2c72fa087f # v1.6.1
        with:
          fail: true
          args: "--config=.lychee.toml ."
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
