name: Trivy Weekly Scan

on:
  schedule:
    - cron: '35 6 * * 6'

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-20.04
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/miracum/ahd2fhir:latest"
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
