name: Trivy Weekly Scan

on:
  schedule:
    - cron: "35 6 * * 6"

permissions: read-all

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-22.04
    permissions:
      security-events: write
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@41f05d9ecffa2ed3f1580af306000f734b733e54 # 0.11.2
        with:
          image-ref: "ghcr.io/miracum/ahd2fhir:latest"
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@83f0fe6c4988d98a455712a27f0255212bba9bd4 # v2.3.6
        with:
          sarif_file: "trivy-results.sarif"
