name: Trivy Weekly Scan

on:
  schedule:
    - cron: "35 6 * * 6"

permissions: read-all

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-22.04
    permissions:
      security-events: write
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@1f0aa582c8c8f5f7639610d6d38baddfea4fdcee # 0.9.2
        with:
          image-ref: "ghcr.io/miracum/ahd2fhir:latest"
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@04df1262e6247151b5ac09cd2c303ac36ad3f62b # v2.2.9
        with:
          sarif_file: "trivy-results.sarif"
