name: validate-fhir-resources

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions: read-all

jobs:
  validate-fhir-resource:
    name: Validate FHIR resources
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@607fce577a46308457984d59e4954e075820f10a # v3.0.3
        with:
          dotnet-version: 6.0.x

      - name: Setup Java JDK
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
        with:
          distribution: "microsoft"
          java-version: "17"

      - name: Install Firely.Terminal
        run: |
          dotnet tool install --global Firely.Terminal --version 3.1.0
          fhir --help

      - name: Restore FHIR package dependencies
        run: |
          fhir restore

      - name: Validate generated FHIR resources
        run: |
          for fhir_file in tests/__snapshots__/**/*.fhir.json; do fhir validate --verbose --fail "$fhir_file"; done
