name: validate-fhir-resources

on:
  pull_request:
    branches:
      - master
      - beta
  push:
    branches:
      - master
      - beta

permissions: read-all

jobs:
  validate-fhir-resource:
    name: Validate FHIR resources
    runs-on: ubuntu-24.04
    container: ghcr.io/miracum/ig-build-tools:v2.1.13@sha256:9e08f8958bfd87b90d5dc63659a69ac33e1ecffe7b6282dc1b06cf221205a840
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Restore FHIR package dependencies
        run: |
          fhir restore

      - name: Validate generated FHIR resources
        run: |
          set -e
          for fhir_file in tests/__snapshots__/**/*.fhir.json; do
            fhir validate --verbose --fail "$fhir_file";
          done
